language: python
matrix:
  include:
    - python: 3.5
      dist: trusty
    - python: 3.6
      dist: trusty
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements/test.txt
  - pip install coveralls
  - gem install mdl
script:
  - coverage run -m unittest discover
  - flake8 canvasapi tests
  - mdl *.md
after_success:
  - coveralls
